language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database transport_test;' -U postgres
  - npm run build
script:
  - npm test
after_success:
  - npm run coverage
